### PR TITLE
Create an abstraction for PeakMemoryUsageThread

### PR DESCRIPTION
**Pull request by srinivasreddy**
closes https://github.com/psf/pyperf/issues/96

### CODE REVIEW

**Review by corona10 — CHANGES_REQUESTED** [review]
https://github.com/psf/pyperf/pull/111/checks?check_run_id=3073460369

See Windows CI

**Comment by vstinner** [comment]
What's the status of tis PR?

**Comment by srinivasreddy** [comment]
I have fixed the build failure . @corona10 needs  to review it. Or @vstinner if you have time, please take a look ?

**Comment by corona10** [comment]
> I have fixed the build failure . @corona10 needs to review it. Or @vstinner if you have time, please take a look ?

Sorry for the late, I will take a look this PR by next week.

**Comment by srinivasreddy** [comment]
No worries @corona10

**Review by corona10 — APPROVED** [review]
lgtm

**Comment by corona10** [comment]
Thanks @srinivasreddy

**Pull request merged**
