### PR TITLE
Travis CI: use Python '3.9'

### PR DESCRIPTION
**Pull request by vstinner**

### CODE REVIEW

**Comment by vstinner** [comment]
Nice, a build on the new travis-ci.com (GitHub Action API) was created: https://travis-ci.com/github/psf/pyperf/builds/193739970

... But it seems like a new for the old travis-ci.org (legacy API) was already created but no build was started...

cc @ewdurbin

**Comment by vstinner** [comment]
On the old website, https://travis-ci.org/organizations/psf/repositories tells me that psf/pyperf is now handled by travis-ci.com.

**Comment by ewdurbin** [comment]
I'm not sure what you need me to do about this?

**Comment by vstinner** [comment]
I removed " continuous-integration/travis-ci " on the branch protection (in the GitHub project admin page).

**Pull request closed without merging**
