### PR TITLE
Fix "std dev" link

### PR DESCRIPTION
**Pull request by vstinner**

### CODE REVIEW

**Comment by fzakaria** [comment]
Does it help just to emit the standard deviation?

I was reading that knowing the standard deviation for a sample set isn't very helpful; I think it gives off the wrong impression that it's used as a confidence interval.

Reading the link - my feeling was the intent was for it to be a 95% confidence interval especially since the t-test value was calcualte.

**Comment by vstinner** [comment]
The PR fix the documentation of the current implementation: describe correctly what's being used.

**Comment by fzakaria** [comment]
sorry i wasn't clear; the output of `stats` has a +- on the standard deviation; that gives the impression like it's the confidence interval no?

**Comment by vstinner** [comment]
cc @corona10

**Comment by corona10** [comment]
I will take a look during the sprint.

**Review by corona10 — APPROVED** [review]
lgtm

**Pull request merged**
