### PR TITLE
Add Python 3.9 support on Travis

### PR DESCRIPTION
**Pull request by abdullahselek**

### CODE REVIEW

**Comment by pablogsal** [comment]
Thanks @abdullahselek !

We can probably wait a couple of days so 3.9 is officially released and we don't need to use `3.9-dev` :)

**Comment by abdullahselek** [comment]
OK, no problem 👍

**Comment by pablogsal** [comment]
> OK, no problem

You can leave the PR open and update it then :)

**Comment by abdullahselek** [comment]
I will keep an eye on Travis, it looks like version 3.9 is not available yet.

**Comment by pablogsal** [comment]
> I will keep an eye on Travis, it looks like version 3.9 is not available yet.

Thanks!

**Comment by vstinner** [comment]
I'm fine with using 3.9-dev for now, and move to 3.9 once Travis CI is updated.

**Comment by vstinner** [comment]
Ah, I didn't notice that the PR was updated to use "3.9" :-) I merged it even if Travis CI didn't run, since Travis CI was stuck for an unknown reason.

**Comment by vstinner** [comment]
Hum. It seems like pyperf is still using the legacy API for Travis CI (travis-ci.org), rather than the new GitHub Action API (travis-ci.com). I'm not sure how to migrate https://travis-ci.org/github/psf/pyperf to https://travis-ci.com/github/psf/pyperf : " This repository may not exist or **you may need to use another account to have access to it** ".

**Comment by vstinner** [comment]
@ewdurbin: Hey, are you able to migrate pyperf by going to https://travis-ci.com/github/psf/pyperf and click on the Migrate button?

**Pull request merged**
